-- Additive operational schema only. Apply manually to the intended PostgreSQL database.
-- No Phase 1 table changes, data cleanup, or provider calls.
BEGIN;

CREATE TABLE IF NOT EXISTS catalog_import_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(32) NOT NULL CHECK (status IN ('PLANNED', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_FAILURES')),
    created_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    last_updated_at timestamp with time zone NOT NULL,
    total_brands integer NOT NULL,
    total_reported_fragrances bigint NOT NULL,
    brands_with_unknown_count integer NOT NULL,
    brands_completed integer NOT NULL,
    brands_failed integer NOT NULL,
    active_batch_token varchar(36)
);

CREATE TABLE IF NOT EXISTS catalog_import_brand_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL,
    brand_slug varchar(255) NOT NULL,
    brand_name text,
    reported_fragrance_count bigint,
    catalog_position integer NOT NULL,
    status varchar(16) NOT NULL CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
    processed_fragrance_count bigint NOT NULL,
    attempt_count integer NOT NULL,
    failure_message varchar(512),
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    last_updated_at timestamp with time zone NOT NULL,
    CONSTRAINT uk_catalog_progress_run_brand UNIQUE (run_id, brand_slug),
    CONSTRAINT uk_catalog_progress_run_position UNIQUE (run_id, catalog_position),
    CONSTRAINT fk_catalog_progress_run FOREIGN KEY (run_id) REFERENCES catalog_import_runs (id)
);

CREATE INDEX IF NOT EXISTS idx_catalog_progress_run_status_position
    ON catalog_import_brand_progress (run_id, status, catalog_position);

COMMIT;
