-- Additive migration for the existing perfume database. Apply manually before the new importer.
-- No provider calls, data deletes, column replacements or existing constraint changes.
BEGIN;

ALTER TABLE perfumes ADD COLUMN IF NOT EXISTS image_url text;

CREATE TABLE IF NOT EXISTS perfume_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id bigint NOT NULL REFERENCES perfumes(id),
    metric_key varchar(255) NOT NULL,
    score numeric,
    category text,
    n_records bigint,
    reliability text,
    scale text,
    derived_from text,
    reviews_count bigint,
    label text,
    details jsonb NOT NULL,
    CONSTRAINT uk_perfume_metrics_key UNIQUE (perfume_id, metric_key)
);

CREATE TABLE IF NOT EXISTS perfume_opinions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id bigint NOT NULL REFERENCES perfumes(id),
    kind varchar(8) NOT NULL CHECK (kind IN ('PRO', 'CON')),
    text_hash varchar(64) NOT NULL,
    opinion_text text NOT NULL,
    source text,
    position integer,
    like_ratio numeric,
    n_records bigint,
    details jsonb NOT NULL,
    CONSTRAINT uk_perfume_opinions_text UNIQUE (perfume_id, kind, text_hash)
);

CREATE TABLE IF NOT EXISTS perfume_similarities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id bigint NOT NULL REFERENCES perfumes(id),
    reference_key varchar(384) NOT NULL,
    related_public_id varchar(128),
    related_fragrance_slug varchar(255),
    related_name text,
    like_ratio numeric,
    n_records bigint,
    position integer,
    details jsonb NOT NULL,
    CONSTRAINT uk_perfume_similarities_target UNIQUE (perfume_id, reference_key)
);
CREATE INDEX IF NOT EXISTS idx_perfume_similarities_target_slug ON perfume_similarities (related_fragrance_slug);

CREATE TABLE IF NOT EXISTS perfume_provider_payloads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id bigint NOT NULL REFERENCES perfumes(id),
    tool_name varchar(64) NOT NULL,
    payload_hash varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    received_at timestamptz NOT NULL,
    CONSTRAINT uk_perfume_provider_payloads_hash UNIQUE (perfume_id, tool_name, payload_hash)
);

CREATE TABLE IF NOT EXISTS perfume_unlayered_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id bigint NOT NULL REFERENCES perfumes(id),
    note_id bigint NOT NULL REFERENCES notes(id),
    position integer,
    CONSTRAINT uk_perfume_unlayered_notes_pair UNIQUE (perfume_id, note_id)
);
CREATE INDEX IF NOT EXISTS idx_perfume_unlayered_notes_note_id ON perfume_unlayered_notes (note_id);

-- UNIQUE indexes already start with perfume_id; no redundant standalone perfume_id indexes.
COMMIT;
